corridas/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('run_update/<int:id>/', views.run_update, name='run_update'),
    path('run_list', views.run_list, name='run_list'),
    path('signup', views.register, name='register')
]

runnup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('corridas.urls')),
]

corridas/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Corridas(models.Model):
    distancia = models.DecimalField(max_digits=5, decimal_places=2)
    tempo = models.TimeField(blank=True, null=True)
    data_da_corrida = models.DateField(null=False, blank=False)
    sentimento = models.CharField(max_length=10, null=True, blank=True)
    observacoes = models.CharField(max_length=400, blank=True, null=True)
    lancado_em = models.DateTimeField(default=timezone.now)
    corredor = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return str(self.distancia)


class Categoria(models.Model):
    nome_categoria = models.CharField(max_length=100,null=False, blank=False)
    distancia_categoria = models.DecimalField(max_digits=6, decimal_places=2)
    imagem_categoria = models.CharField(max_length=250, null=True, blank=True)
    corredor_categoria = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return str(self.nome_categoria)

corridas/forms.py
from django import forms
from .models import Corridas
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CorridasForm(forms.ModelForm):
    class Meta:
        model = Corridas
        fields = ["distancia", "tempo", "data_da_corrida", "sentimento", "observacoes"]


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

corridas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Corridas
from .forms import CorridasForm,CreateUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator
import datetime


@login_required()
def dashboard(request):
    if request.method == 'POST':
        form = CorridasForm(request.POST)
        if form.is_valid():
            formu = form.save(commit=False)
            formu.corredor = request.user
            formu.save()
            messages.success(request, 'Corrida Adicionada com sucesso')
            return redirect('dashboard')
    else:
        form = CorridasForm()

    mes = datetime.datetime.now()
    corridas = Corridas.objects.filter(corredor=request.user, data_da_corrida__month = mes.month).order_by('-data_da_corrida')
    return render(request, 'dashboard.html', {'corridas':corridas, 'form':form})


@login_required()
def run_update(request, id):
	corridas = get_object_or_404(Corridas, pk=id)
	form = CorridasForm(request.POST or None, instance=corridas)
	if form.is_valid():
		formu = form.save(commit=False)
		formu.corredor = request.user
		formu.save()
		return redirect('dashboard')
	return render(request,'run_update.html', {'corridas':corridas,'form':form})


@login_required()
def run_list(request):
	mes = datetime.datetime.now()
	corridas_list = Corridas.objects.filter(corredor=request.user, data_da_corrida__year = mes.year).order_by('-data_da_corrida')
	paginator = Paginator(corridas_list, 2)

	page = request.GET.get('page')
	corridas = paginator.get_page(page)
	return render(request, 'run_list.html', {'corridas':corridas})


def register(request):
	if request.user.is_authenticated:
		return redirect('dashboard')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('login')
			

		context = {'form':form}
		return render(request, 'registration/signup.html', context)

corridas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>RunnUp::Sua corrida, seu desafio</title>


    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<body class="grey lighten-5">

{% if user.is_authenticated %}
<nav class="orange darken-4">
  <div class="nav-wrapper">
    <a href="{% url 'dashboard' %}" class="brand-logo">RunnUp</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="#!"> <i class="material-icons left">tag_faces</i>Perfil</a></li>
      <li><a href="{% url 'logout' %}"> <i class="material-icons left">clear</i>Sair</a></li>
      <li><a href="{% url 'run_list' %}"> <i class="material-icons left">directions_run</i>Todas Corridas</a></li>
    </ul>
    <ul class="side-nav" id="mobile-demo">
      <li><a href="#!"> <i class="material-icons left">tag_faces</i>Perfil</a></li>
      <li><a href="{% url 'logout' %}"> <i class="material-icons left">clear</i>Sair</a></li>
      <li><a href="{% url 'run_list' %}"> <i class="material-icons left">directions_run</i>Todas Corridas</a></li>
    </ul>
  </div>
</nav>
{% endif %}
      

    {% block main %}
        

    {% endblock main %}

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src=" {% static 'js/materialize.min.js' %}"></script>
    <script>
      $(".button-collapse").sideNav();

      //modal
      $(document).ready(function(){
      // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
      $('.modal').modal();
        
      });

      $('.datepicker').pickadate({
      selectMonths: true, // Creates a dropdown to control month
      selectYears: 15, // Creates a dropdown of 15 years to control year,

      // Título dos botões de navegação
      labelMonthNext: 'Próximo Mês',
      labelMonthPrev: 'Mês Anterior',

      // Meses e dias da semana
      monthsFull: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      monthsShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
      weekdaysFull: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
      weekdaysShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],

      // Letras da semana
      weekdaysLetter: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],

      today: 'Hoje',
      clear: 'Limpar',
      close: 'Ok',
      closeOnSelect: 'false', // Close upon selecting a date,
      container: 'body', // ex. 'body' will append picker to body

      format: 'dd/mm/yyyy'
      
    });
    </script>

</body>
</html>

corridas/templates/dashboard.html
{% extends 'base.html' %}


{% block main %}
   

{% for corrida in corridas %}

<div class="row">
    <div class="col s12 m4 l4">
        <div class="card-panel card hoverable white">
          <h5>Atividade do dia: {{corrida.data_da_corrida|date:'d-m-Y'}}</h5>
            <table class="centered">
                <tbody>
                <tr>
                    <td>
                        <h5>{{corrida.distancia}} Km</h5>
                        <h6 class="grey-text">Distância</h6>
                    </td>

                    <td>
                      <h5>{{corrida.sentimento}}</h5>
                      <h6 class="grey-text">Sentimento</h6>
                    </td>
                </tr>
                </tbody>
            </table>

            <div class="card-action center-align">
              <a class="btn orange darken-4 waves-effect waves-light" href="{% url 'run_update' corrida.id %}"><i class="material-icons">create</i> Editar </a>
            </div>

        </div>
    </div>
</div>

{% endfor %}

<div class="row">
    <div class="col s12 m5 right-align">
        <div class="fixed-action-btn">
            <!-- Modal Trigger -->
            <a href="#modal1" class="modal-trigger btn-floating btn-large waves-effect waves-light center-align orange darken-4"><i class="material-icons">add</i></a>
        </div>
    </div>
</div>


<!-- Modal Structure -->
<div id="modal1" class="modal">
<div class="modal-content">
  <div class="row">
      <form method="POST">
          {% csrf_token %}
    <div class="input-field col s12">
      <label for="distancia">Distância</label>
      <input type="text" class="validate" name="distancia" id="id_distancia" required />
    </div>
    <div class="input-field col s12">
      <input type="time" step="1" name="tempo" id="hora" placeholder="id_tempo">
    </div>
    <div class="input-field col s12">
        <input type="text" class="datepicker" name="data_da_corrida" id="id_data_da_corrida" placeholder="Data da Corrida" required />
    </div>
    <div class="input-field col s12">
        <input type="text" class="validate" name="sentimento" id="id_sentimento" placeholder="Sentimento" />
    </div>
    <div class="input-field col s12">
        <input type="text" class="validate" name="observacoes" id="id_observacoes" placeholder="Observações" />
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="submit" id="btnEnviar" class="modal-action modal-close btn orange darken-4 waves-effect waves-light">Salvar</button>
  <a class="modal-action modal-close btn red darken-4 waves-effect waves-light">Cancelar</a>
  <!--<a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>-->
</div>
</form>
</div>

<script>
  var distancia = document.getElementById("id_distancia");
  var botao = document.getElementById("btnEnviar");
  botao.addEventListener('click', function () {
    dist = distancia.value;
    distancia.value = dist.replace(",", ".");
  })	
</script>

{% endblock main %}

corridas/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
        </div>
      </nav>
    

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>

</body>
</html>

corridas/templates/run_list.html
{% extends 'base.html' %}


{% block main %}
   

{% for corrida in corridas %}

<div class="row">
    <div class="col s12 m4 l4">
        <div class="card-panel card hoverable white">
          <h5>Atividade do dia: {{corrida.data_da_corrida|date:'d-m-Y'}}</h5>
            <table class="centered">
                <tbody>
                <tr>
                    <td>
                        <h5>{{corrida.distancia}} Km</h5>
                        <h6 class="grey-text">Distância</h6>
                    </td>

                    <td>
                      <h5>{{corrida.sentimento}}</h5>
                      <h6 class="grey-text">Sentimento</h6>
                    </td>
                </tr>
                </tbody>
            </table>

            <div class="card-action center-align">
              <a class="btn orange darken-4 waves-effect waves-light" href="{% url 'run_update' corrida.id %}"><i class="material-icons">create</i> Editar </a>
            </div>

        </div>
    </div>
</div>


{% endfor %}

<div class="row">
  <ul class="pagination center-align">

    {% if corridas.has_previous  %}
      <li class="waves-effect"><a href="?page={{corridas.previous_page_number}}"><i class="material-icons">chevron_left</i></a></li>
      <li class="waves-effect"><a href="?page={{corridas.previous_page_number}}"> {{corridas.previous_page_number}} </a></li>
    {% endif %}

    <li class="active orange darken-4"><a href="#!"> {{ corridas.number }} </a></li>
      
    {% if corridas.has_next %}
      <li class="waves-effect"> <a href="?page={{ corridas.next_page_number }}"> {{ corridas.next_page_number }} </a></li>
      <li class="waves-effect"><a href="?page={{ corridas.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
    {% endif %}

  </ul>
</div>


<script>
  var distancia = document.getElementById("id_distancia");
  var botao = document.getElementById("btnEnviar");
  botao.addEventListener('click', function () {
    dist = distancia.value;
    distancia.value = dist.replace(",", ".");
  })	
</script>

{% endblock main %}

corridas/templates/run_update.html
{% extends 'base.html' %}


{% block main %}

<div class="row">
    <form method="POST">
        {% csrf_token %}
  <div class="input-field col s12">
    <label for="distancia">Distância</label>
    <input type="text" class="validate" name="distancia" id="id_distancia" value="{{corridas.distancia}}" required />
  </div>
  <div class="input-field col s12">
    <input type="time" step="1" name="tempo" id="hora" placeholder="id_tempo" value="{{corridas.tempo}}">
  </div>
  <div class="input-field col s12">
      <input type="text" class="datepicker" name="data_da_corrida" id="id_data_da_corrida" placeholder="Data da Corrida" value="{{corridas.data_da_corrida|date:'d/m/Y'}}" required />
  </div>
  <div class="input-field col s12">
      <input type="text" class="validate" name="sentimento" id="id_sentimento" value="{{corridas.sentimento}}" placeholder="Sentimento" />
  </div>
  <div class="input-field col s12">
      <input type="text" class="validate" name="observacoes" id="id_observacoes" value="{{corridas.observacoes}}" placeholder="Observações" />
  </div>
</div>

<button type="submit" id="btnEnviar" class="btn orange darken-4 waves-effect waves-light">Salvar</button>
<a class="modal-action modal-close btn red darken-4 waves-effect waves-light" href=" {% url 'dashboard' %} ">Cancelar</a>

</form>

<script>
  var distancia = document.getElementById("id_distancia");
  var botao = document.getElementById("btnEnviar");
  botao.addEventListener('click', function () {
    dist = distancia.value;
    distancia.value = dist.replace(",", ".");
  })	
</script>

{% endblock main %}